version: "3.8"

services:
  database:
    image: postgres:14.1-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
      interval: 10s
      timeout: 15s
      retries: 30 
    env_file:
      - .env
    networks:
        - bdd-network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 15432:15432
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database
    networks:
        - bdd-network

volumes:
  pgadmin:
    driver: local

networks:
    api-rust-network:
    bdd-network:
