version: "3.8"

services:
  database:
    image: postgres:14.1-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 15432:15432
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database

volumes:
  pgadmin:
    driver: local
